from __future__ import annotations

import xml.etree.ElementTree as ET
from pathlib import Path
from typing import Iterable, List, Tuple

from ..jsonio import dump_json, ensure_dir
from ..models import ValidatedCandidate, dataclass_to_dict


def write_xdf_bundle(
    output_dir: str | Path,
    accepted_candidates: List[ValidatedCandidate],
    title: str = "Generated ECU XDF",
    description: str = "Best-effort XDF generated by ecu-xdf-assistant",
) -> tuple[Path, Path]:
    out_dir = ensure_dir(output_dir)
    xdf_path = out_dir / "generated.xdf"
    sidecar_path = out_dir / "xdf_sidecar.json"

    root = ET.Element("XDFFORMAT", {"version": "2.0"})
    header = ET.SubElement(root, "XDFHEADER")
    ET.SubElement(header, "deftitle").text = title
    ET.SubElement(header, "description").text = description
    ET.SubElement(header, "author").text = "ecu-xdf-assistant"
    ET.SubElement(header, "baseoffset").text = "0"

    next_unique_id = 0x1000
    for candidate in accepted_candidates:
        if candidate.candidate_type == "map" and candidate.rows and candidate.cols:
            next_unique_id = _append_table(root, candidate, next_unique_id)
        elif candidate.candidate_type == "scalar":
            next_unique_id = _append_constant(root, candidate, next_unique_id)

    _indent(root)
    ET.ElementTree(root).write(xdf_path, encoding="utf-8", xml_declaration=True)

    dump_json(sidecar_path, [dataclass_to_dict(item) for item in accepted_candidates])
    return xdf_path, sidecar_path


def _append_table(root: ET.Element, candidate: ValidatedCandidate, unique_id: int) -> int:
    table = ET.SubElement(root, "XDFTABLE", {"uniqueid": f"0x{unique_id:X}"})
    unique_id += 1

    ET.SubElement(table, "title").text = candidate.name
    ET.SubElement(table, "description").text = _join_text(candidate.notes, fallback="Generated map candidate")
    ET.SubElement(table, "CATEGORYMEM", {"index": "0", "category": candidate.semantic_group})

    x_axis = ET.SubElement(table, "XDFAXIS", {"id": "x"})
    ET.SubElement(x_axis, "indexcount").text = str(candidate.cols)
    ET.SubElement(x_axis, "units").text = ""
    ET.SubElement(x_axis, "decimalpl").text = "0"
    ET.SubElement(x_axis, "datatype").text = _datatype_code(candidate.signed)
    ET.SubElement(x_axis, "outputtype").text = "1"
    _embedded_data(
        parent=x_axis,
        address=candidate.axis_x_address or candidate.address,
        element_size_bits=candidate.element_size_bits,
        row_count=1,
        major_stride_bits=candidate.element_size_bits,
        minor_stride_bits=candidate.element_size_bits,
    )
    ET.SubElement(x_axis, "MATH", {"equation": "X"})

    y_axis = ET.SubElement(table, "XDFAXIS", {"id": "y"})
    ET.SubElement(y_axis, "indexcount").text = str(candidate.rows)
    ET.SubElement(y_axis, "units").text = ""
    ET.SubElement(y_axis, "decimalpl").text = "0"
    ET.SubElement(y_axis, "datatype").text = _datatype_code(candidate.signed)
    ET.SubElement(y_axis, "outputtype").text = "1"
    _embedded_data(
        parent=y_axis,
        address=candidate.axis_y_address or candidate.address,
        element_size_bits=candidate.element_size_bits,
        row_count=1,
        major_stride_bits=candidate.element_size_bits,
        minor_stride_bits=candidate.element_size_bits,
    )
    ET.SubElement(y_axis, "MATH", {"equation": "X"})

    z_axis = ET.SubElement(table, "XDFAXIS", {"id": "z"})
    ET.SubElement(z_axis, "indexcount").text = str(candidate.rows * candidate.cols)
    ET.SubElement(z_axis, "units").text = candidate.units or ""
    ET.SubElement(z_axis, "decimalpl").text = str(_decimal_places(candidate.scale_expression))
    ET.SubElement(z_axis, "datatype").text = _datatype_code(candidate.signed)
    ET.SubElement(z_axis, "outputtype").text = "1"
    _embedded_data(
        parent=z_axis,
        address=candidate.address,
        element_size_bits=candidate.element_size_bits,
        row_count=candidate.rows,
        major_stride_bits=candidate.cols * candidate.element_size_bits,
        minor_stride_bits=candidate.element_size_bits,
    )
    ET.SubElement(z_axis, "MATH", {"equation": candidate.scale_expression})

    return unique_id


def _append_constant(root: ET.Element, candidate: ValidatedCandidate, unique_id: int) -> int:
    constant = ET.SubElement(root, "XDFCONSTANT", {"uniqueid": f"0x{unique_id:X}"})
    unique_id += 1

    ET.SubElement(constant, "title").text = candidate.name
    ET.SubElement(constant, "description").text = _join_text(candidate.notes, fallback="Generated scalar candidate")
    ET.SubElement(constant, "CATEGORYMEM", {"index": "0", "category": candidate.semantic_group})
    ET.SubElement(constant, "units").text = candidate.units or ""
    ET.SubElement(constant, "decimalpl").text = str(_decimal_places(candidate.scale_expression))
    ET.SubElement(constant, "datatype").text = _datatype_code(candidate.signed)
    ET.SubElement(constant, "outputtype").text = "1"
    _embedded_data(
        parent=constant,
        address=candidate.address,
        element_size_bits=candidate.element_size_bits,
        row_count=1,
        major_stride_bits=candidate.element_size_bits,
        minor_stride_bits=candidate.element_size_bits,
    )
    ET.SubElement(constant, "MATH", {"equation": candidate.scale_expression})
    return unique_id


def _embedded_data(
    parent: ET.Element,
    address: int,
    element_size_bits: int,
    row_count: int,
    major_stride_bits: int,
    minor_stride_bits: int,
) -> None:
    ET.SubElement(
        parent,
        "EMBEDDEDDATA",
        {
            "mmedaddress": f"0x{address:X}",
            "mmedelementsizebits": str(element_size_bits),
            "mmedmajorstridebits": str(major_stride_bits),
            "mmedminorstridebits": str(minor_stride_bits),
            "mmedrowcount": str(row_count),
            "mmedtypeflags": "0",
        },
    )


def _datatype_code(signed: bool) -> str:
    return "1" if signed else "0"


def _decimal_places(expression: str) -> int:
    if "." not in expression:
        return 0
    decimals = expression.split(".")[-1]
    digits = []
    for char in decimals:
        if char.isdigit():
            digits.append(char)
        else:
            break
    return min(len(digits), 6)


def _join_text(lines: List[str], fallback: str = "") -> str:
    return "; ".join(line for line in lines if line) or fallback


def _indent(elem: ET.Element, level: int = 0) -> None:
    i = "\n" + level * "  "
    if len(elem):
        if not elem.text or not elem.text.strip():
            elem.text = i + "  "
        for child in elem:
            _indent(child, level + 1)
        if not child.tail or not child.tail.strip():
            child.tail = i
    if level and (not elem.tail or not elem.tail.strip()):
        elem.tail = i
